# Stream Chemistry Changes Pre and Post Hurricane Hugo

## Background
This analysis reproduces figure 3 from Schaefer et al. (2000), which shows stream chemistry changes in four Puerto Rican streams pre and post Hurricane Hugo.

## Data
Raw water chemistry data .csv files were sourced from McDowell and International Institute Of Tropical Forestry (IITF) (2024).

## Methods
Raw water chemistry data for four sample sites were processed as follows: 

- Data for each site were cleaned. 

- Moving averages for each ion of interest at were calculated for each site for every 9 weeks during the sampling period. The moving_average() function was created to automate this step.

- Data for each site were joined together into one data frame.

## Results
Water chemistry data for the period of interest were plotted for each site.

Chemistry data for each ion are displayed in separate graphs.
```{r}
# Plotting smoothed and joined data for all sites together ---------------

sites_smoothed_joined_plot <- sites_smoothed_joined |>
  pivot_longer(
    cols = c(NH4N_ugL, Ca_mgL, Mg_mgL, NO3N_ugL, K_mgL),
    names_to = "ion",
    values_to = "concentration"
  )

ggplot(
  data = sites_smoothed_joined_plot,
  mapping = aes(
    x = window_start,
    y = concentration,
    color = site_ID
  )
) +
  geom_point() +
  geom_line() +
  scale_x_date(name = "Years") +
  facet_wrap(~ion, scales = "free")
```